fn main() {
    // This command list is the source of the `allow-`/`deny-` permissions under
    // `permissions/autogenerated/`, which it rewrites on every build. `tauri-build` also
    // globs that directory on its own, so either one alone keeps the application command ACL
    // closed. See AGENTS.md section 5 for what it actually takes to reopen it.
    //
    // Every command in `invoke_handler!` belongs in this list, and each one also needs the
    // matching `allow-` identifier in `capabilities/default.json` — a widening that
    // AGENTS.md section 5 requires the pull request to state.
    let attributes = tauri_build::Attributes::new()
        .app_manifest(tauri_build::AppManifest::new().commands(&["core_version"]));
    // `expect` rather than bare `build()`, which takes no attributes. Bare `build()` also
    // prints a hint that this crate has fallen behind the CLI; keep it, since the two are
    // pinned in different lockfiles and drift on their own.
    tauri_build::try_build(attributes).expect(
        "failed to run tauri-build; an `unknown field` here means `@tauri-apps/cli` has \
         outrun the locked `tauri-build` — run `cargo update`",
    );
}
