fn main() {
    // This command list is the source of the `allow-`/`deny-` permissions under
    // `permissions/autogenerated/`. Those files, not this call, are what keeps the
    // application command ACL closed: `tauri-build` globs `permissions/**/*` regardless, so
    // enforcement survives even if this reverts to bare `tauri_build::build()`. See
    // AGENTS.md section 5, which records the measurement.
    //
    // Every command in `invoke_handler!` belongs in this list, and each one also needs the
    // matching `allow-` identifier in `capabilities/default.json` — a widening that
    // AGENTS.md section 5 requires the pull request to state.
    let attributes = tauri_build::Attributes::new()
        .app_manifest(tauri_build::AppManifest::new().commands(&["core_version"]));
    tauri_build::try_build(attributes).expect("failed to run tauri-build");
}
