//! The application command ACL's correspondence check (#30, #24).
//!
//! A command is exposed by four edits that nothing ties together: the `#[tauri::command]`
//! attribute, its entry in `generate_handler!`, its name in `build.rs`'s `commands(...)`,
//! and an `allow-` grant in a capability. Only a grant naming an undefined identifier fails
//! the build. A command registered but not granted builds clean and is rejected at the IPC
//! boundary the first time the frontend invokes it; a command removed but left in the
//! manifest goes on defining a permission a stale grant validates against. This test makes
//! both fail.
//!
//! Reachability is asked of Tauri's own resolver, built from the same context the application
//! runs with, so a grant that is present but does not reach the main window —
//! a capability `tauri.conf.json` does not enable, another window, a remote origin, a
//! `deny-` — counts as no grant. The source-side sets are read as text, and every shape
//! the reader does not understand fails rather than reading as empty.

use std::collections::BTreeSet;
use std::path::Path;

const SRC: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/src");
const BUILD_RS: &str = include_str!("../build.rs");
const LIB_RS: &str = include_str!("lib.rs");
/// What `tauri-build` actually loaded, written by this build's `build.rs`.
const ACL_MANIFESTS: &str = include_str!(concat!(env!("OUT_DIR"), "/acl-manifests.json"));
/// The window `tauri.conf.json` opens; it sets no label, so Tauri names it `main`.
const WINDOW: &str = "main";

const FIX: &str = "A command the WebView should call needs all four: `#[tauri::command]`, \
    an entry in `generate_handler!` (src/lib.rs), its name in `commands(...)` (build.rs), \
    and its `allow-` grant in capabilities/default.json — the grant is a widening the pull \
    request must state (AGENTS.md section 5). A command it should not call needs none of \
    them; when removing one, delete its file under permissions/autogenerated/ by hand.";

fn rust_files(dir: &Path, out: &mut Vec<(String, String)>) {
    for entry in std::fs::read_dir(dir).expect("src/ is readable") {
        let path = entry.expect("readable entry").path();
        if path.is_dir() {
            rust_files(&path, out);
        } else if path.extension().is_some_and(|x| x == "rs")
            && path != Path::new(SRC).join("acl.rs")
        {
            // Not this file: it is compiled only into tests, and it spells every needle.
            let text = std::fs::read_to_string(&path).expect("readable source");
            out.push((path.display().to_string(), text));
        }
    }
}

/// Lines with `//` comments removed, so a mention in prose is not a registration. A `/*`
/// comment is not removed; the readers below refuse one where it could hide an entry.
fn code(text: &str) -> String {
    text.lines()
        .map(|line| line.split("//").next().unwrap_or(""))
        .collect::<Vec<_>>()
        .join("\n")
}

fn ident(s: &str) -> bool {
    !s.is_empty() && s.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
}

/// Asserts `needle` occurs exactly once across `files`' code, so that a second call — in
/// another file, or spelled as a path rather than a method — cannot go unread.
fn once(files: &[(String, String)], needle: &str) {
    let hits: Vec<_> = files
        .iter()
        .flat_map(|(file, text)| std::iter::repeat_n(file, code(text).matches(needle).count()))
        .collect();
    assert_eq!(
        hits.len(),
        1,
        "expected `{needle}` once, found it in {hits:?}"
    );
}

/// Every function carrying `#[tauri::command]`, by the name Tauri registers it under.
fn annotated() -> BTreeSet<String> {
    let mut files = Vec::new();
    rust_files(Path::new(SRC), &mut files);
    let mut names = BTreeSet::new();
    for (file, text) in files {
        // Any other spelling — `cfg_attr(.., tauri::command)`, an imported `#[command]` —
        // would apply the attribute without this reader seeing it.
        let lines_with_it = text
            .lines()
            .map(str::trim)
            .filter(|l| l.starts_with("#[tauri::command"))
            .count();
        assert!(
            code(&text).matches("tauri::command").count() == lines_with_it
                && !text.lines().any(|l| l.trim().starts_with("#[command")),
            "{file} names `tauri::command` other than as a line-leading `#[tauri::command]`"
        );
        let mut lines = text.lines().map(str::trim);
        while let Some(line) = lines.next() {
            if !line.starts_with("#[tauri::command") {
                continue;
            }
            // `rename_all` renames arguments; a bare `rename` would rename the command,
            // which this reader does not follow.
            let attribute = line.split(']').next().unwrap_or(line);
            let args = attribute.replace("rename_all", "");
            assert!(
                !args.contains("rename"),
                "{file}: `{line}` renames a command, which this check does not read"
            );
            let decl = if line.contains("fn ") {
                line
            } else {
                lines
                    .by_ref()
                    .find(|l| !l.starts_with("#[") && !l.starts_with("///"))
                    .unwrap_or_else(|| panic!("{file}: `{line}` is followed by no item"))
            };
            let name = decl
                .split("fn ")
                .nth(1)
                .and_then(|rest| rest.split(['(', '<']).next())
                .filter(|n| ident(n))
                .unwrap_or_else(|| panic!("{file}: `{decl}` after `{line}` is not a plain fn"));
            assert!(
                names.insert(name.to_string()),
                "{file}: two commands named {name}"
            );
        }
    }
    names
}

/// The commands in the one `generate_handler!`, by the last segment of each path.
fn registered() -> BTreeSet<String> {
    let mut files = Vec::new();
    rust_files(Path::new(SRC), &mut files);
    // `Builder::invoke_handler` replaces the previous handler, so a second one would make
    // this list a lie rather than an addition.
    once(&files, "invoke_handler");
    once(&files, "generate_handler");
    let lib = code(LIB_RS);
    let block = lib
        .split("tauri::generate_handler![")
        .nth(1)
        .expect("src/lib.rs has the `tauri::generate_handler![`");
    let block = block.split(']').next().expect("generate_handler! closes");
    assert!(
        !block.contains("/*"),
        "generate_handler! holds a `/*` comment"
    );
    let mut names = BTreeSet::new();
    for path in block.split(',').map(str::trim).filter(|p| !p.is_empty()) {
        let name = path.rsplit("::").next().unwrap_or(path);
        assert!(
            ident(name),
            "generate_handler! entry `{path}` is not a path"
        );
        assert!(names.insert(name.to_string()), "{name} is registered twice");
    }
    names
}

/// The string literals in `build.rs`'s `commands(&[...])`.
fn listed() -> BTreeSet<String> {
    once(&[("build.rs".into(), BUILD_RS.into())], "commands(");
    let build = code(BUILD_RS);
    let list = build
        .split(".commands(&[")
        .nth(1)
        .expect("build.rs passes `.commands(&[...])` a literal list");
    let list = list.split(']').next().expect("the list closes");
    assert!(!list.contains("/*"), "build.rs's list holds a `/*` comment");
    let mut names = BTreeSet::new();
    for item in list.split(',').map(str::trim).filter(|i| !i.is_empty()) {
        let name = item
            .strip_prefix('"')
            .and_then(|i| i.strip_suffix('"'))
            .filter(|n| ident(n))
            .unwrap_or_else(|| panic!("build.rs lists `{item}`, which is not a name literal"));
        assert!(
            names.insert(name.to_string()),
            "build.rs lists {name} twice"
        );
    }
    names
}

/// The commands the application permission manifest defines a permission for, whatever
/// file under `permissions/` that permission came from.
fn defined() -> BTreeSet<String> {
    let manifests: serde_json::Value =
        serde_json::from_str(ACL_MANIFESTS).expect("acl-manifests.json parses");
    let app = &manifests["__app-acl__"];
    assert!(app.is_object(), "no application permission manifest");
    assert!(
        app["default_permission"].is_null(),
        "the application manifest has a default permission, which this check does not read"
    );
    assert!(
        app["permission_sets"]
            .as_object()
            .is_none_or(|sets| sets.is_empty()),
        "the application manifest has permission sets, which this check does not read"
    );
    let mut names = BTreeSet::new();
    for (id, permission) in app["permissions"].as_object().expect("permissions") {
        for key in ["allow", "deny"] {
            for command in permission["commands"][key]
                .as_array()
                .expect("command list")
            {
                names.insert(command.as_str().expect("a command name").to_string());
            }
        }
        assert!(
            permission["scope"].is_null() || permission["scope"] == serde_json::json!({}),
            "{id} carries a scope, which this check does not read"
        );
    }
    names
}

fn diff(a: &BTreeSet<String>, b: &BTreeSet<String>) -> Vec<String> {
    a.difference(b).cloned().collect()
}

#[test]
fn every_command_is_registered_listed_defined_and_reachable_from_the_window() {
    let annotated = annotated();
    let registered = registered();
    let listed = listed();
    let defined = defined();
    assert!(!registered.is_empty(), "no command is registered");

    for (what, set) in [
        ("carries `#[tauri::command]`", &annotated),
        ("is in build.rs's `commands(...)`", &listed),
        ("has a permission under permissions/", &defined),
    ] {
        let missing = diff(&registered, set);
        let extra = diff(set, &registered);
        assert!(
            missing.is_empty() && extra.is_empty(),
            "registered in generate_handler! but not one that {what}: {missing:?}; \
             {what} but not registered: {extra:?}. {FIX}"
        );
    }

    // `runtime_authority_mut` is `doc(hidden)` and marked unstable; `resolve_access` is the
    // public check the IPC boundary itself runs. Pinned by Cargo.lock, so a Tauri update
    // that moves either breaks this test's build rather than its meaning.
    let mut context = crate::context();
    let windows: Vec<_> = context
        .config()
        .app
        .windows
        .iter()
        .map(|w| &w.label)
        .collect();
    assert_eq!(
        windows,
        [WINDOW],
        "this check asks about the `{WINDOW}` window only"
    );
    let authority = context.runtime_authority_mut();
    let unreachable: Vec<_> = registered
        .iter()
        .filter(|c| {
            authority
                .resolve_access(c, WINDOW, WINDOW, &tauri::ipc::Origin::Local)
                .is_none()
        })
        .collect();
    assert!(
        unreachable.is_empty(),
        "registered but not granted to the `{WINDOW}` window's local origin by any \
         capability tauri.conf.json enables: {unreachable:?}. {FIX}"
    );
}
