//! The shell's half of consent: the presenter the core asks.
//!
//! The mechanism is decided (`docs/decisions.md`, "Consent is a native dialog the core
//! owns"): a native `NSAlert` driven from Rust through `objc2`, with the negative button
//! added first so the affirmative is never the default, and the alert held so the core can
//! abort the modal when it withdraws a request. Nothing in the application needs a dialog
//! until the shell tool (#16) lands, so this module ships the pure half — the button list
//! and the mapping from the first slot to *decline*, tested on their values — and a
//! presenter that fails closed. Wiring `NSAlert` replaces [`FailClosed`] in the pull request
//! that first needs it; the tests here pin what that wiring must preserve.
//!
//! What must never appear here: an application command that takes an approval decision,
//! or a `dialog:` permission in `capabilities/default.json`. `tests` checks both.

use stanchion_core::consent::presenter::{
    Answer, ConsentPresenter, Handle, PresenterError, Rendered, Responder,
};
use stanchion_core::consent::{AFFIRMATIVE, NEGATIVE};

/// The captions in the order a native alert receives them. `NSAlert` makes the first button
/// added the default (Return), so the negative goes first.
pub fn buttons() -> [&'static str; 2] {
    [NEGATIVE, AFFIRMATIVE]
}

/// Maps the index of the button the user pressed to an answer. Getting the order in
/// [`buttons`] right without this mapping would execute on the Deny click. Any other slot —
/// a response code the alert was not built with — is no answer at all.
pub fn answer_for_slot(slot: usize) -> Option<Answer> {
    match slot {
        0 => Some(Answer::Decline),
        1 => Some(Answer::Allow),
        _ => None,
    }
}

/// The presenter the application runs with until the native alert is wired: it can show
/// nothing, so nothing is approved. The core treats `Err` from `show` as presenter failure
/// and executes nothing.
pub struct FailClosed;

impl ConsentPresenter for FailClosed {
    fn capacity(&self) -> usize {
        0
    }

    fn show(&self, _: &Rendered, _: Responder) -> Result<Handle, PresenterError> {
        Err(PresenterError("no native presenter is wired yet".into()))
    }

    fn dismiss(&self, _: Handle) {}
}

#[cfg(test)]
mod tests {
    use super::*;

    const CAPABILITY: &str = include_str!("../capabilities/default.json");

    #[test]
    fn the_button_list_is_negative_first() {
        assert_eq!(buttons(), ["Deny", "Allow"]);
    }

    #[test]
    fn the_first_slot_maps_to_decline_and_nothing_else_maps_to_allow() {
        assert_eq!(answer_for_slot(0), Some(Answer::Decline));
        assert_eq!(answer_for_slot(1), Some(Answer::Allow));
        assert_eq!(answer_for_slot(2), None);
        assert_eq!(answer_for_slot(usize::MAX), None);
    }

    #[test]
    fn the_capability_grants_no_dialog_permission() {
        // `tauri-plugin-dialog` hands its result back to the WebView, which is the path the
        // decision closes. Its identifiers are `dialog:...`.
        assert!(
            !CAPABILITY.contains("\"dialog:"),
            "capabilities/default.json grants a dialog permission"
        );
    }

    #[test]
    fn the_capability_grants_no_approval_shaped_command() {
        for word in ["approve", "consent", "allow-answer", "decision"] {
            assert!(
                !CAPABILITY
                    .to_ascii_lowercase()
                    .contains(&format!("allow-{word}")),
                "capabilities/default.json grants an approval-shaped command: {word}"
            );
        }
    }

    #[test]
    fn the_application_manifest_is_not_empty() {
        // #24: with no application permission manifest Tauri skips the ACL check entirely.
        let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/permissions/autogenerated");
        let entries: Vec<_> = std::fs::read_dir(dir)
            .expect("permissions/autogenerated exists")
            .filter_map(Result::ok)
            .filter(|e| e.path().extension().is_some_and(|x| x == "toml"))
            .collect();
        assert!(!entries.is_empty(), "no autogenerated permission files");
    }

    #[test]
    fn the_fail_closed_presenter_shows_nothing() {
        assert_eq!(FailClosed.capacity(), 0);
    }
}
